create table public.visitors (
  id uuid primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  visit_count integer not null default 0 check (visit_count >= 0),
  trace_count integer not null default 0 check (trace_count >= 0),
  created_at timestamptz not null default now()
);

create table public.traces (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 500),
  visitor_id uuid not null references public.visitors(id),
  created_at timestamptz not null default now(),
  user_agent text,
  referrer text
);

create table public.visit_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.visitors(id),
  path text not null check (char_length(path) between 1 and 200),
  user_agent text,
  referrer text,
  created_at timestamptz not null default now()
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index traces_created_at_idx on public.traces (created_at desc);
create index traces_visitor_id_idx on public.traces (visitor_id);
create index visit_events_created_at_idx on public.visit_events (created_at desc);
create index visit_events_visitor_id_idx on public.visit_events (visitor_id);

alter table public.visitors enable row level security;
alter table public.traces enable row level security;
alter table public.visit_events enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.record_visit(
  p_visitor_id uuid,
  p_path text,
  p_user_agent text,
  p_referrer text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.visitors (id, first_seen, last_seen, visit_count)
  values (p_visitor_id, now(), now(), 1)
  on conflict (id) do update set
    last_seen = now(),
    visit_count = visitors.visit_count + 1;

  if not exists (
    select 1 from public.visit_events
    where visitor_id = p_visitor_id
      and path = p_path
      and created_at > now() - interval '5 minutes'
  ) then
    insert into public.visit_events (visitor_id, path, user_agent, referrer)
    values (p_visitor_id, left(p_path, 200), left(p_user_agent, 500), left(p_referrer, 500));
  end if;
end;
$$;

create or replace function public.create_trace(
  p_visitor_id uuid,
  p_message text,
  p_user_agent text,
  p_referrer text
) returns public.traces
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_trace public.traces;
begin
  perform pg_advisory_xact_lock(7442);

  if not exists (select 1 from public.visitors where id = p_visitor_id) then
    raise exception 'visitor_not_found';
  end if;

  if exists (
    select 1 from public.traces
    where visitor_id = p_visitor_id
      and created_at > now() - interval '1 hour'
  ) then
    raise exception 'visitor_rate_limited';
  end if;

  if (
    select count(*) from public.traces
    where created_at > now() - interval '1 minute'
  ) >= 20 then
    raise exception 'global_rate_limited';
  end if;

  insert into public.traces (message, visitor_id, user_agent, referrer)
  values (trim(p_message), p_visitor_id, left(p_user_agent, 500), left(p_referrer, 500))
  returning * into inserted_trace;

  update public.visitors
  set trace_count = trace_count + 1, last_seen = now()
  where id = p_visitor_id;

  return inserted_trace;
end;
$$;

revoke all on function public.record_visit(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.create_trace(uuid, text, text, text) from public, anon, authenticated;
grant execute on function public.record_visit(uuid, text, text, text) to service_role;
grant execute on function public.create_trace(uuid, text, text, text) to service_role;
